<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
	<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	<PackageReference Include="Serilog.Sinks.Map" Version="2.0.0" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	<PackageReference Include="Serilog.Expressions" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ARMCommon">
      <HintPath>..\..\AxExtend\ARMCommon.dll</HintPath>
    </Reference>
    <Reference Include="AxExtend">
      <HintPath>..\..\AxExtend\AxExtend.dll</HintPath>
    </Reference>
  </ItemGroup>


</Project>
